[platformio]
default_envs = due, esp32
src_dir = arduino
include_dir = arduino/include

[env]
framework = arduino
monitor_speed = 115200
build_src_filter =
    -<*>
    +<src/*.c>
    +<platformio/main.cpp>

[env:due]
platform = atmelsam@8.3.0
board = due
lib_deps = https://github.com/bdmihai/DueFreeRTOS.git#e6a3354cb0b337d8215ccf162e90a5fb9a50d241
build_src_filter =
    ${env.build_src_filter}
    +<ports/due/board_port.c>
build_flags =
    -Wl,--wrap=vApplicationMallocFailedHook
    -Wl,--wrap=vApplicationStackOverflowHook
    -Wl,--wrap=vAssertBlink

[env:esp32]
platform = espressif32@6.12.0
board = esp32dev
build_src_filter =
    ${env.build_src_filter}
    +<ports/esp32/board_port.c>
